// Package key generates, writes, and loads age X25519 identities.
package key

import (
	"bufio"
	"bytes"
	"errors"
	"io"
	"os"
	"strings"

	"filippo.io/age"
)

// Identity is an age X25519 identity loaded or generated by this package.
type Identity struct {
	age *age.X25519Identity
}

func Generate() (*Identity, error) {
	id, err := age.GenerateX25519Identity()
	if err != nil {
		return nil, err
	}
	return &Identity{age: id}, nil
}

// Create generates an identity and writes it with O_EXCL, then Chmod 0600.
// It never truncates an existing file.
func Create(path string) (*Identity, error) {
	id, err := Generate()
	if err != nil {
		return nil, err
	}
	f, err := os.OpenFile(path, os.O_WRONLY|os.O_CREATE|os.O_EXCL, 0o600)
	if err != nil {
		if errors.Is(err, os.ErrExist) {
			return nil, ErrIdentityExists
		}
		return nil, err
	}
	_, werr := io.WriteString(f, id.age.String()+"\n")
	cerr := f.Close()
	if werr != nil {
		return nil, werr
	}
	if cerr != nil {
		return nil, cerr
	}
	// os.WriteFile/O_CREATE supply a mode only at creation, so writing over a
	// stale world-readable identity.txt would leave it world-readable. O_EXCL
	// removes that case; keep both.
	if err := os.Chmod(path, 0o600); err != nil {
		return nil, err
	}
	return id, nil
}

// Load parses path with age.ParseIdentities and rejects anything that is not
// exactly one *age.X25519Identity.
func Load(path string) (*Identity, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, err
	}
	ids, err := age.ParseIdentities(bytes.NewReader(data))
	if err != nil {
		if nonCommentLines(data) == 0 {
			return nil, ErrNotSingleIdentity
		}
		// age quotes the identity line; never return or wrap that error.
		return nil, ErrInvalidIdentity
	}
	if len(ids) != 1 {
		return nil, ErrNotSingleIdentity
	}
	x25519, ok := ids[0].(*age.X25519Identity)
	if !ok {
		return nil, ErrNotX25519
	}
	return &Identity{age: x25519}, nil
}

func (id *Identity) AgeIdentity() age.Identity {
	return id.age
}

func (id *Identity) Recipient() age.Recipient {
	return id.age.Recipient()
}

var (
	ErrIdentityExists    = errors.New("identity file already exists")
	ErrNotSingleIdentity = errors.New("identity file must contain exactly one identity")
	ErrNotX25519         = errors.New("identity is not an X25519 identity")
	ErrInvalidIdentity   = errors.New("identity file is invalid")
)

func nonCommentLines(data []byte) int {
	n := 0
	s := bufio.NewScanner(bytes.NewReader(data))
	for s.Scan() {
		line := s.Text()
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		n++
	}
	return n
}
